# Generated by Django 4.1.4 on 2022-12-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
