# Generated by Django 4.1.4 on 2022-12-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappedproduct',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='rating',
            field=models.FloatField(),
        ),
    ]
