# Generated by Django 4.0.5 on 2022-12-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_scrappedproduct_rating_alter_search_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
