# Generated by Django 4.0.5 on 2023-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sastodeal_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastodeal_product',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
