# Generated by Django 4.0.5 on 2023-01-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_recommend_product_sastodeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend_product_socheko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500, null=True)),
                ('rating', models.FloatField()),
                ('link', models.ImageField(default='link', upload_to='image')),
                ('dprice', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='socheko_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500, null=True)),
                ('rating', models.FloatField()),
                ('link', models.ImageField(default='link', upload_to='image')),
                ('dprice', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
