# Generated by Django 4.0.5 on 2023-01-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_recommend_product_socheko_socheko_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
