# Generated by Django 4.1.5 on 2023-01-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_reviewratingrdaraz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRatingRDaraz',
        ),
    ]
